### ISSUE TITLE
Run test against newer versions of React

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/accessible-autocomplete#668]
## What

Run our React tests against updated versions of [the React example](https://github.com/alphagov/accessible-autocomplete/blob/main/examples/react/index.html) loading the following versions of React:
- 16.0
- 17.0
- 18.0 (be aware of [changes of the API for rendering components on the page](https://react.dev/blog/2022/03/29/react-v18#new-client-and-server-rendering-apis))

Update the 'Using with React' section with the result, in a similar fashion that the React section mentions its versions.

## Why

Newer versions of React have been released since we last wrote the tests and it'll be good to let our users know whether we're compatible or not.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] We ran tests against React 16 - #681
- [x] We ran tests against React 17 - #682
- [x] We ran tests against React 18 - #683
- [ ] We updated the README - #684
